### ISSUE TITLE
Synchronized writer

### ISSUE THREAD

**Issue by withakay** [hanswolff/simple.mailserver#1]
Hi,
I was playing around with your SMTP server project and in my stress testing I kept running into problems with the program trying to access an object that had been disposed.

I track this down to an issue in BaseConnection.cs the underlying problem being that Streams are not thread safe
I made a small change to lock the stream when writing to it and the problem went away, my change is below. 

``` csharp
public async Task WriteLineAsyncAndFireEvents(string line)
{
            if (Writer.BaseStream.CanWrite)
            {
                RawLineSent(this, new RawLineEventArgs(Writer.Encoding.GetBytes(line)));            
                // previously did:
                // await Writer.WriteLineAsync(line);
                // updated to this:
                await TextWriter.Synchronized(Writer).WriteLineAsync(line);
            }
}
```

I should note this problem only showed up when I threw thousands of connections at the SMTP Server

**Comment by hanswolff** [comment]
Thanks for pointing that out. It is fixed in a8e31f426618f229dd9c218065bf1750c9d84b3d
